//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02_DayOfWeekService.ConsoleClient.DayOfWeekService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DayOfWeekService.IDayOfWeek")]
    public interface IDayOfWeek {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfWeek/GetDayOWeek", ReplyAction="http://tempuri.org/IDayOfWeek/GetDayOWeekResponse")]
        string GetDayOWeek(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfWeek/GetDayOWeek", ReplyAction="http://tempuri.org/IDayOfWeek/GetDayOWeekResponse")]
        System.Threading.Tasks.Task<string> GetDayOWeekAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDayOfWeekChannel : _02_DayOfWeekService.ConsoleClient.DayOfWeekService.IDayOfWeek, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DayOfWeekClient : System.ServiceModel.ClientBase<_02_DayOfWeekService.ConsoleClient.DayOfWeekService.IDayOfWeek>, _02_DayOfWeekService.ConsoleClient.DayOfWeekService.IDayOfWeek {
        
        public DayOfWeekClient() {
        }
        
        public DayOfWeekClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DayOfWeekClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfWeekClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfWeekClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayOWeek(System.DateTime date) {
            return base.Channel.GetDayOWeek(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayOWeekAsync(System.DateTime date) {
            return base.Channel.GetDayOWeekAsync(date);
        }
    }
}
