//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _05_SubstringsCountService.ConsoleApp.SubstringsCountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SubstringsCountService.ISubstringsCountService")]
    public interface ISubstringsCountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubstringsCountService/GetSubstringsCount", ReplyAction="http://tempuri.org/ISubstringsCountService/GetSubstringsCountResponse")]
        int GetSubstringsCount(string firstString, string secondString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubstringsCountService/GetSubstringsCount", ReplyAction="http://tempuri.org/ISubstringsCountService/GetSubstringsCountResponse")]
        System.Threading.Tasks.Task<int> GetSubstringsCountAsync(string firstString, string secondString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubstringsCountServiceChannel : _05_SubstringsCountService.ConsoleApp.SubstringsCountService.ISubstringsCountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubstringsCountServiceClient : System.ServiceModel.ClientBase<_05_SubstringsCountService.ConsoleApp.SubstringsCountService.ISubstringsCountService>, _05_SubstringsCountService.ConsoleApp.SubstringsCountService.ISubstringsCountService {
        
        public SubstringsCountServiceClient() {
        }
        
        public SubstringsCountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubstringsCountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubstringsCountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubstringsCountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetSubstringsCount(string firstString, string secondString) {
            return base.Channel.GetSubstringsCount(firstString, secondString);
        }
        
        public System.Threading.Tasks.Task<int> GetSubstringsCountAsync(string firstString, string secondString) {
            return base.Channel.GetSubstringsCountAsync(firstString, secondString);
        }
    }
}
