var arrayLiteral = [1, 2, 3];
	booleanLiteral = true;
	integerLiteral = 5;
	floatLiteral = 5.1;
	objectLiteral = { myCar: "Opel", brand: "Tigra", hp: 96, engineVolume: 1.4 };
	stringLiteral = "some text";
console.log('Type of arrayLiteral: ' + typeof(arrayLiteral));
console.log('Type of booleanLiteral: ' + typeof(booleanLiteral));
console.log('Type of integerLiteral: ' + typeof(integerLiteral));
console.log('Type of floatLiteral: ' + typeof(floatLiteral));
console.log('Type of objectLiteral: ' + typeof(objectLiteral));
console.log('Type of stringLiteral: ' + typeof(stringLiteral));